// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/v1/account.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Result with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Result) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Code

	// no validation rules for Message

	if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ResultValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ResultValidationError is the validation error returned by Result.Validate if
// the designated constraints aren't met.
type ResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResultValidationError) ErrorName() string { return "ResultValidationError" }

// Error satisfies the builtin error interface
func (e ResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResultValidationError{}

// Validate checks the field values on Empty with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Empty) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// EmptyValidationError is the validation error returned by Empty.Validate if
// the designated constraints aren't met.
type EmptyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmptyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmptyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmptyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmptyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmptyValidationError) ErrorName() string { return "EmptyValidationError" }

// Error satisfies the builtin error interface
func (e EmptyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmpty.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmptyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmptyValidationError{}

// Validate checks the field values on SmsLoginReq with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *SmsLoginReq) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetMobile()) < 1 {
		return SmsLoginReqValidationError{
			field:  "Mobile",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetCode()) < 1 {
		return SmsLoginReqValidationError{
			field:  "Code",
			reason: "value length must be at least 1 runes",
		}
	}

	return nil
}

// SmsLoginReqValidationError is the validation error returned by
// SmsLoginReq.Validate if the designated constraints aren't met.
type SmsLoginReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SmsLoginReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SmsLoginReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SmsLoginReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SmsLoginReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SmsLoginReqValidationError) ErrorName() string { return "SmsLoginReqValidationError" }

// Error satisfies the builtin error interface
func (e SmsLoginReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSmsLoginReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SmsLoginReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SmsLoginReqValidationError{}

// Validate checks the field values on SmsLoginResp with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *SmsLoginResp) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Token

	return nil
}

// SmsLoginRespValidationError is the validation error returned by
// SmsLoginResp.Validate if the designated constraints aren't met.
type SmsLoginRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SmsLoginRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SmsLoginRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SmsLoginRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SmsLoginRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SmsLoginRespValidationError) ErrorName() string { return "SmsLoginRespValidationError" }

// Error satisfies the builtin error interface
func (e SmsLoginRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSmsLoginResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SmsLoginRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SmsLoginRespValidationError{}

// Validate checks the field values on MiniLoginReq with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *MiniLoginReq) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetCode()) < 1 {
		return MiniLoginReqValidationError{
			field:  "Code",
			reason: "value length must be at least 1 runes",
		}
	}

	return nil
}

// MiniLoginReqValidationError is the validation error returned by
// MiniLoginReq.Validate if the designated constraints aren't met.
type MiniLoginReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MiniLoginReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MiniLoginReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MiniLoginReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MiniLoginReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MiniLoginReqValidationError) ErrorName() string { return "MiniLoginReqValidationError" }

// Error satisfies the builtin error interface
func (e MiniLoginReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMiniLoginReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MiniLoginReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MiniLoginReqValidationError{}

// Validate checks the field values on MiniLoginResp with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *MiniLoginResp) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Token

	if v, ok := interface{}(m.GetUserInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MiniLoginRespValidationError{
				field:  "UserInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// MiniLoginRespValidationError is the validation error returned by
// MiniLoginResp.Validate if the designated constraints aren't met.
type MiniLoginRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MiniLoginRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MiniLoginRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MiniLoginRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MiniLoginRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MiniLoginRespValidationError) ErrorName() string { return "MiniLoginRespValidationError" }

// Error satisfies the builtin error interface
func (e MiniLoginRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMiniLoginResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MiniLoginRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MiniLoginRespValidationError{}

// Validate checks the field values on UserInfo with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UserInfo) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetNickName()) < 1 {
		return UserInfoValidationError{
			field:  "NickName",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetAvatarUrl()) < 1 {
		return UserInfoValidationError{
			field:  "AvatarUrl",
			reason: "value length must be at least 1 runes",
		}
	}

	return nil
}

// UserInfoValidationError is the validation error returned by
// UserInfo.Validate if the designated constraints aren't met.
type UserInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserInfoValidationError) ErrorName() string { return "UserInfoValidationError" }

// Error satisfies the builtin error interface
func (e UserInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserInfoValidationError{}

// Validate checks the field values on UpdatesUserReq with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *UpdatesUserReq) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for NickName

	// no validation rules for AvatarUrl

	return nil
}

// UpdatesUserReqValidationError is the validation error returned by
// UpdatesUserReq.Validate if the designated constraints aren't met.
type UpdatesUserReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatesUserReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatesUserReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatesUserReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatesUserReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatesUserReqValidationError) ErrorName() string { return "UpdatesUserReqValidationError" }

// Error satisfies the builtin error interface
func (e UpdatesUserReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdatesUserReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatesUserReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatesUserReqValidationError{}

// Validate checks the field values on GetByIDReq with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *GetByIDReq) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	return nil
}

// GetByIDReqValidationError is the validation error returned by
// GetByIDReq.Validate if the designated constraints aren't met.
type GetByIDReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetByIDReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetByIDReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetByIDReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetByIDReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetByIDReqValidationError) ErrorName() string { return "GetByIDReqValidationError" }

// Error satisfies the builtin error interface
func (e GetByIDReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetByIDReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetByIDReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetByIDReqValidationError{}

// Validate checks the field values on GetByIDResp with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *GetByIDResp) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetByIDRespValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// GetByIDRespValidationError is the validation error returned by
// GetByIDResp.Validate if the designated constraints aren't met.
type GetByIDRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetByIDRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetByIDRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetByIDRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetByIDRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetByIDRespValidationError) ErrorName() string { return "GetByIDRespValidationError" }

// Error satisfies the builtin error interface
func (e GetByIDRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetByIDResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetByIDRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetByIDRespValidationError{}

// Validate checks the field values on UserModel with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UserModel) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	return nil
}

// UserModelValidationError is the validation error returned by
// UserModel.Validate if the designated constraints aren't met.
type UserModelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserModelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserModelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserModelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserModelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserModelValidationError) ErrorName() string { return "UserModelValidationError" }

// Error satisfies the builtin error interface
func (e UserModelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserModel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserModelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserModelValidationError{}
