// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"context"
	"github.com/comeonjy/account/configs"
	"github.com/comeonjy/account/internal/data"
	"github.com/comeonjy/account/internal/server"
	"github.com/comeonjy/account/internal/service"
	"github.com/comeonjy/go-kit/pkg/xlog"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, logger *xlog.Logger) *App {
	configsInterface := configs.NewConfig(ctx)
	dataData := data.NewData(configsInterface, logger)
	accountRepo := data.NewAccountRepo(dataData)
	accountService := service.NewAccountService(configsInterface, accountRepo, logger)
	grpcServer := server.NewGrpcServer(accountService, configsInterface, logger)
	httpServer := server.NewHttpServer(ctx, configsInterface, logger)
	app := newApp(ctx, grpcServer, httpServer, configsInterface)
	return app
}
